[package]
name = "tauri-plugin-persisted-scope"
version = "0.1.0"
description = "Save filesystem and asset scopes and restore them when the app is reopened."
authors.workspace = true
license.workspace = true
edition.workspace = true
rust-version.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde.workspace = true
serde_json.workspace = true
tauri.workspace = true
log.workspace = true
thiserror.workspace = true
bincode = "1"

[features]
protocol-asset = [ "tauri/protocol-asset" ]